name: Deploy

on:
  workflow_call:
    inputs:
      token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy bot
        run: node dist/index.js
        env:
          DISCORD_TOKEN: ${{ inputs.token }}
