name: Deploy to Discord

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build Docker image
        run: docker build -t my-discord-bot .
      - name: Run Docker container
        run: docker run -d -p 8080:8080 my-discord-bot
