name: Discord Bot Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # ดาวน์โหลดเฉพาะ commit ล่าสุด 2 ครั้ง
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
        working-directory: ./my-bot  # สมมติว่าโค้ดบอทอยู่ใน folder my-bot
      - name: Build
        run: npm run build
        working-directory: ./my-bot
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-build
      - name: Deploy
        uses: ./.github/workflows/deploy.yml  # ใช้ workflow ย่อยสำหรับการ deploy
        with:
          token: ${{ secrets.DISCORD_TOKEN }}
          
