name: Discord Bot Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
        working-directory: ./
      - name: Deploy
        uses: ./.github/workflows/
        with:
          token: ${{ secrets.DISCORD_TOKEN }}
