name: Discord Bot Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        # เพิ่มขั้นตอนการ build แอปพลิเคชันของคุณที่นี่
        # เช่น ถ้าคุณใช้ TypeScript อาจจะใช้:
        # run: npx tsc
      - name: Start bot
        run: node index.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          
