name: Discord Bot Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx tsc
      - name: Build Docker image
        run: docker build -t my-discord-bot .
      - name: Run Docker container
        run: docker run -d -p 8080:8080 my-discord-bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

