name: Deploy to Discord

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        uses: ./.github/workflows  # เปลี่ยน my-action เป็นชื่อไฟล์ของคุณ
        with:
          token: ${{ secrets.DISCORD_TOKEN }}
          
